server.port=9090

## PostgreSQL
##spring.datasource.url=jdbc:postgresql://localhost:5432/deliverydb
spring.datasource.url=jdbc:postgresql://db:5432/deliverydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.connectionTimeout=20000

server.error.include-message=always

##Single thread
## Set the core and max pool size as 1, and queueCapacity as 0, to make it as a single thread
#threadCorePoolSize.corePoolSize=1
#threadCorePoolSize.maxPoolSize=1
#threadCorePoolSize.queueCapacity=0


##Multiple threads
threadCorePoolSize.corePoolSize=3
threadCorePoolSize.maxPoolSize=6
threadCorePoolSize.queueCapacity=30

